In [1]:
import pandas as pd
import numpy as np

from sklearn.impute import SimpleImputer

In [2]:
diabetes = pd.read_csv(r'C:\Users\Shaleen\Desktop\jpnb\datasets\diabetes_processed.csv')
diabetes.head(10)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6.0,148.0,72.000000,35.0,219.028414,33.6,0.627,50.0,1
1,1.0,85.0,66.000000,29.0,70.341550,26.6,0.351,31.0,0
2,8.0,183.0,64.000000,32.0,270.573172,23.3,0.672,32.0,1
3,1.0,89.0,66.000000,23.0,94.000000,28.1,0.167,21.0,0
4,0.0,137.0,40.000000,35.0,168.000000,43.1,2.288,33.0,1
5,5.0,116.0,74.000000,32.0,127.840221,25.6,0.201,30.0,0
6,3.0,78.0,50.000000,32.0,88.000000,31.0,0.248,26.0,1
7,10.0,115.0,72.405184,32.0,136.570245,35.3,0.134,29.0,0
8,2.0,197.0,70.000000,45.0,543.000000,30.5,0.158,53.0,1
9,8.0,125.0,96.000000,32.0,155.571480,32.0,0.232,54.0,1

In [3]:
diabetes_features = diabetes.drop('Outcome', axis=1)
diabetes_label = diabetes[['Outcome']]
diabetes_features.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,6.0,148.0,72.0,35.0,219.028414,33.6,0.627,50.0
1,1.0,85.0,66.0,29.0,70.341550,26.6,0.351,31.0
2,8.0,183.0,64.0,32.0,270.573172,23.3,0.672,32.0
3,1.0,89.0,66.0,23.0,94.000000,28.1,0.167,21.0
4,0.0,137.0,40.0,35.0,168.000000,43.1,2.288,33.0

In [5]:
mask = np.random.randint(0,100, size=diabetes_features.shape).astype(np.bool)
mask = np.logical_not(mask)

In [7]:
diabetes_features[mask] = np.nan
diabetes_features.head(15)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,6.0,148.0,72.000000,35.0,219.028414,33.6,0.627,50.0
1,1.0,85.0,66.000000,29.0,70.341550,26.6,0.351,31.0
2,8.0,183.0,64.000000,32.0,270.573172,23.3,0.672,32.0
3,1.0,89.0,66.000000,23.0,94.000000,28.1,0.167,21.0
4,0.0,137.0,40.000000,35.0,168.000000,43.1,2.288,33.0
5,5.0,116.0,74.000000,32.0,127.840221,25.6,0.201,30.0
6,3.0,78.0,50.000000,32.0,88.000000,31.0,0.248,26.0
7,10.0,115.0,72.405184,32.0,136.570245,35.3,0.134,29.0
8,2.0,197.0,70.000000,45.0,543.000000,30.5,0.158,53.0
9,8.0,125.0,96.000000,32.0,NaN,32.0,0.232,54.0
10,4.0,110.0,92.000000,32.0,124.381180,37.6,0.191,30.0
11,10.0,168.0,74.000000,32.0,254.857463,38.0,0.537,34.0
12,10.0,139.0,80.000000,32.0,186.390349,27.1,1.441,57.0
13,1.0,189.0,60.000000,23.0,846.000000,30.1,0.398,59.0
14,5.0,166.0,72.000000,19.0,175.000000,25.8,0.587,51.0

In [8]:
diabetes_features.isnull().sum()

Pregnancies                 9
Glucose                     5
BloodPressure               9
SkinThickness               5
Insulin                     9
BMI                         4
DiabetesPedigreeFunction    6
Age                         4
dtype: int64

In [9]:
from sklearn.pipeline import make_pipeline
from sklearn.compose import ColumnTransformer

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

In [10]:
x_train, x_test, y_train, y_test = train_test_split(diabetes_features, diabetes_label, test_size=0.2)

In [11]:
transformer = ColumnTransformer(
      transformers=[('features', SimpleImputer(strategy='mean'),[0, 1, 2, 3, 4, 5, 6, 7])]
)

In [12]:
clf = make_pipeline(transformer, DecisionTreeClassifier(max_depth=4))

In [13]:
clf = clf.fit(x_train, y_train)
clf.score(x_train, y_train)

0.7899022801302932

In [14]:
y_pred = clf.predict(x_test)

In [15]:
from sklearn.metrics import accuracy_score
accuracy_score(y_pred, y_test)

0.7467532467532467